### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by Neko-Life** [NekosCloud/MicroCord#1]
Some files are empty. i thought those won't be included on runtime so what's the point in keeping it. Delete them all.

#### ps.
Those are spam

#### pss.
Those empty files i mean

#### psss.
This is my good first issue in this repo

#### pssss.
I dunno what to do

#### psssss.
**REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE**

**Comment by 0t4u** [comment]
No. They are not pointless. Those empty files are preparation for future features. (Translation: I started making something then got lazy)
